* herman's braindump
This braindump adopted very similar approach (and same hugo theme) of [[braindump.jethro.dev][Jethro Kuan's braindump]]. The notes are taken with [[https://www.orgroam.com/][org-roam]] ,another package that Jethro Kuan written. I'm almost a fan of his.

* How to build
This should be easier to build than [[https://github.com/jethrokuan/braindump][jethrokuan/braindump]], for I used similar approach to [[https://www.youtube.com/watch?v=AfkrzFodoNw&t=1513s#0][org-mode website tutorial]] that is slightly simpler in setup

** for github repo
if you want to take this repo and directly push it to your repo, here's how you can do it:
1. delete all files under ~./org~, and fill in your own posts
2. make sure after your modification
   1. you have a ~./org/_index.org~
      it should have head property ~#+HUGO_SECTION:~ so it would not be saved in ~./content/post/_index.md~
   2. you have a ~./org/search/_index.org~
      it should have head property ~#+HUGO_SECTION:search~ so it would be saved in ~./content/search/_index.md~
3. push the repo to github. (and the action + publish.el should do the rest for you!)

** for local
if you want to host it on your own, you can do the following:
1. modify the ~./org~ folder like above
2. in ~publish.el~:
   1. exec ~hermanhel/braindump-publish~
   2. exec the ~setq~ for ~files~ list
   3. exec the ~dolist~ at bottom of the file.
      this would produce the ~./content~ folder.
3. under ~./~ do ~hugo server~, and a server at ~localhost:1313~ should be at your service. You can ~hugo -D~ to create the static website and stuff according to [[https://gohugo.io/getting-started/quick-start/][usage of hugo]]
