:PROPERTIES:
:ID:       63662D42-26CC-47B2-B049-BC4046FB304D
:END:
#+title: XJTLU-Y2S1
#+HUGO_SECTION:main
This is the overall plan and navigation of my academic life in Y2S1 in XJTLU.
The Whole Y2S1 project is constructed in 2 aspects:
+ University Modules
  the modules I enrolled in
  + [[id:F989F96D-F5C2-4DCA-935D-63C673F041A2][CPT101]]
    Computer System
  + [[id:1C716C73-DC8E-45EA-A998-42DDE75C338D][CPT103]]
    Discrete Mathematics
  + [[id:5813D47F-4268-46DA-B99A-C529E2BCBFAD][CPT107]]
    Database System
  + [[id:50A687F9-9642-4A7B-94F3-156F97D6D40D][CPT111]]
    Java Programming
  + [[id:B67886C1-BBAB-4141-8B19-0297F7BE42BA][EAP121]]
    Academic English
+ Self Involved Academic Activities
  Other things I do with the University and/or fellow students with academic aims
  This could be easily messed up with my owned projects, the difference is:
  - SIAC is with academic aim.
    That is, for me, with aim into neuralscience and computer science, with not only the goal of enrich my knowledge/have fun, but also of gaining credits. Examples are =papers, contests, research under professor's instructions=
  - SIAC is with other academic people
    Usually SIAC is with fellow students and professors. in respect of the audience, SIAC would be judged finally by the audiance of scholars. with the academic aim, SIAC is [[id:FFEB6023-94FB-4C85-A14E-928E3114CFF9][Finite Game]], with and watched by fellow scholars.
    
  - The Naviagtion of SIACs:
