:PROPERTIES:
:ID:       E339CEF9-FCFA-414A-BC08-787F5C3039CF
:END:
#+title: principle
#+HUGO_SECTION:main
*Principles* are guidelines drew from recognition of =if...then...= or =cause and effect relationship=.
Upon such recognition, the way leads to ideal condition becomes *Principles* and should be recorded
* Formation
from =errors= and =experiances= comes =facts=.
=Facts= contains =decision= and =result=
from personal belief and reality comes =goals=, =of choice= or =of performance=.
=goals= contains =specific goal= and =requirement=
an act =with principle= make decisions on what strategy/thing to do *base on reality, look to goals*. That is, in combination of =requirement= and =result=, referencing the =decisions=

When patterns are =recognized= and =reasoned=, =stated principle= may be addressed. They, however, could be dangerous while helpful, so must be treated with care, including double check on their =reality image=, =goal hierachy= or =reason=. Don't let them mislead you to a god-knows-where direction.
* A detailed log
[[id:C32FC3FE-BC3B-4A9A-83E9-DD704FAC29FE][2022-02-19]] Morning page
* A collection
** Accumulation works, burst don't
Burst sometimes do a lot. But it happens randomly, making it imposible to count on. And that's of creation.

Of learning, Accumulation totally beat burst.

** 09:37 PM - Take one each time :principle: 
:LOGBOOK:
CLOCK: [2022-02-19 Sat 21:37]--[2022-02-19 Sat 21:41] =>  0:04
:END:
Should not walk into work without principle.

To keep awareness, at least one principle should be taken into the work.

To test principles, should test a new principle each time.

** jump in without doc/blackbox would result in blindness :task:general:principle:untested:
:LOGBOOK:
CLOCK: [2022-02-19 Sat 21:50]--[2022-02-19 Sat 21:53] =>  0:03
:END:

I have it derived from my prior experiance of clojure. Basically, I went through everything, but ended up very blind about what I went through.

Also, when trying out and writing code, jumpping in only kept me up with the code for about half page. I can't remember what I had written. Graph/outline with doc would be very good aid.

** Sleep before ten if tomorow is to work               :principle:untested:life:performance: 
:LOGBOOK:
CLOCK: [2022-02-19 Sat 21:58]--[2022-02-19 Sat 22:01] =>  0:03
:END:
This should be accompanied with proper work-out. If not having my energy used, it can be hard to go to sleep.
*** fact
If I sleep later than 23:00, I mostly get up with depressed mood around noon. The work could start at late afternoon, or not at all.

If I'm all on myself, and want to do meaningful work the other day, sleep early would be nice.

*** goal
This boost my performance of everything.

** Always state principle with clear image              :principle:untested: 
:LOGBOOK:
CLOCK: [2022-02-20 Sun 11:22]--[2022-02-20 Sun 11:23] =>  0:01
:END:

Principle without clear image have no relation to fact/reality, making it unreliable.

