:PROPERTIES:
:ID:       915BC87F-6B2D-4A8A-B65A-B3BE51CE7D45
:END:
#+title: XJTLU Rules
#+HUGO_SECTION:main

* 入学手册
:LOGBOOK:
CLOCK: [2021-12-30 Thu 22:29]--[2022-01-03 Mon 19:51] => 93:22
:END:
欢迎各位加入XXXXX大学。XXXXX大学致力于 =打造国际化科研学习环境，培养具有国际视野和竞争力的世界公民。=
本手册将为你提供一些享受大学生活，实现自我成长的建议。在无其他特定通知或条件下，建议严格遵守本手册内容。
** 作业
在XXXXX大学就读期间，你将被要求完成一些课程作业。
*** 按时完成
理想状态下，请严格提前或按时提交作业。作业是衡量学习进度的重要标志。默认情况下，最多容忍5天的晚交情况。请务必在此之前提交作业，否则后果自负。
*** 提交形式
除建筑系等一些特定学科，所有的课程作业都将在学校课程资源网站LLO（Learning Live Online）上完成。学校有且只有LLO一个作业提交网站。如未在LLO成功提交作业，视同未提交作业处理。
*** 
** 国际化氛围
*** 肤色
你可能在学校里看到各种肤色和人种的老师和同学，这是完全正常的，本大学致力于打造国际化科研学习环境。在看到不熟悉外貌的老师或者同学时，请不要惊慌，或者采取喧哗、骚扰或者殴打等不当应对方式，应该像应对任何熟悉的人种，如非裔、亚裔或者欧裔师生一样应对。作为世界公民，对于多元化环境的适应是非常重要的。
**** 身体器官
本条同样适用于拥有异常身体器官的师生。本学校的设施尽量考虑了多元人群的使用，但仍可能有出于各种原因，无法合适使用学校设施的师生。请在力所能及范围内对他们谅解或帮助。
**** 例外
以上条款不适用于任何拥有XXXX和XXXXXXX的师生。如在任何时间发现具有以上特点的人员在校内逗留，请立刻通知学校物业进行处理，并尽量不被发现地离开现场，但请尽量不要离开学校。
*** 政治
学校是新鲜思想的摇篮。你可以在校内除IB外的任何地点讨论任何合适的观点。校内的商店不被视作校内。如果认为观点将是不合适的，请不要在上述例外地点或校外进行讨论，否则后果自负。
**** （隐藏）限度
学校的观点保护有着限度
** 校园
*** 校区
XXXXX大学有且仅有一个校区。学校南端地下室为人防措施，并不通向任何其他校区，地下室尽头墙壁的另一头也并非学校的地产。
请不要相信任何关于“南校区”或者任何不属于1.3.2所述教学楼的传言。也请不要传播他们，这只会给学校管理带来困扰。
如在任何场所看见描述 “南校区”或者暗示“南校区”存在的材料，请立即通知学校物业进行处理。
**** （隐藏）地下通道的墙和尽头的划痕、标语和声音

*** 教学楼
学校现有且仅有一个基础教学楼Elementary Building，四个科学学科楼Science Building A/B/C/D，两个数学学科楼Mathematic Building A/B，一个公共教学楼Shared Building，以及两个电子学科教学楼Eelectronic Building A/B。
*** 图书馆
学校现有且仅有一个图书馆，位于学校中心的中心楼Middle Building东侧3-10层。请不要相信或进入任何学校内除MB内图书馆以外的图书馆附属设施，图书馆并没有设置任何其他校内阅览室。
** 时间
*** 通宵
请尽量避免在校通宵。学校的工作时段为8:00-17:00。
如特殊情况必须在校通宵，请使用特定的通宵教室。学校物业的保安会清理所有其他的教室，并驱赶所有逗留学生。他们是为了学生的安全着想，请一定听从他们的指示。
禁止在非通宵教室通宵。
**** 意外情况
z一般来说，通宵教室是安全的。学校物业的保安会定期在通宵教室检查和巡视。
当有突发意外情况时，请相信学校保安，并听从他们的指示。他们经过训练，并了解学校情况。
即使你不认为发生了任何意外情况，也请相信学校保安，并听从他们的指示。
当你在非通宵教室通宵并遇见意外情况，通宵教室的保安不能也无法保证你的安全，请不要前往通宵教室寻求帮助。请在教室隐蔽处等待险情过去。如果你希望得到帮助，请尽力前往位于校园南端的地下室。
** 寝室
*** 校内
学校目前无任何校内寝室。任何在校内逗留至21:00以后的师生都被视为已知并在通宵条例的庇护之下。
*** 校外
学校人员目前使用且仅使用附近的WA，WB，WC三个大学集中宿舍。学校不提供任何其他的住宿地点。师生可以自行在校外居住。

* 元素

** 疫情
疫情可以是谜题的解，或者线索，工具

*** 疫情间的封锁地段
IR地下一层停车场，SX楼的封锁门，地下广场
保安哨卡

** 世界公民
世界公民可以是谜题的解，或者一个核心概念
先暂定为谜题的解。
*** XXXXX大学致力培养世界公民。
任何无法成为世界公民的世界公民候选人都将成为大学的一部分（打造国际化研究学习环境），并为大学培养世界公民提供助力。（留校:)）
南校区为这些人准备。
另一种说法是，XXXXX大学本来只是普通的大学。从南校区开始的异变使学生开始变化。
另一种说法是，XXXXX大学理念中的世界公民包括在世界中的一切智慧体，包括理念体，灵体，以及地球及非地球本土有/无机生命体。
另一种说法是，XXXXX大学的理念体觉醒之后（有一个异变开始的时间点），规则和外部理念世界运行的规则开始交织。作为XXXXX大学的理念体的存在存在于所有相信“世界公民”概念的智慧体上，并以可能性的方式影响其周边世界的规则。存在感越强，则遵循XXXXX大学理念规则的可能性越高。为了延续自己的存在，XXXXX大学的理念体尝试通过认知污染的方式传播“世界公民”理念。
另一种说法是，International Building IB有一切问题的答案。包括 “世界公民”的真相。
*** XXXXX大学的成员
由中国的X市XX大学和英国的Kidneylake大学合办。在两边的校园都有异变产生。
大学逐渐开始沟通除了人类之外的智慧体。所有大学成员将会为 “世界公民” 而非 “世界部分公民” 的理念身份准备。从原则上来说，唯一离开大学的条件是成为 “世界公民” 。任何不满足条件的成员都将被困在大学内部，或者不断回到大学。经过时间越长，成员就会越将自己认知为大学的一部分。”“世界公民” 身份和 ”“大学”的存在是相辅相成的，所以大学不会将所有人都困在大学内部，也不会把所有人都放走。
所有大学成员都会把各自认知为合理的大学成员。无法进行此类认知的大学成员将会被处理。
*** 世界规则
外部理念世界是一个大的理念世界框架。整个世界由理念体构成。XXXXX大学的 “世界公民” 理念与理念世界的 “世界” 理念相调谐，引发理念规则改变和认知习惯形成。世界是一个更大的 “大学”。
**** 时空逻辑
世界的状态是无限的。每一个世界的状态都是无尽的世界状态可能海洋中的一滴随机的水。
理念是生活在状态中的生物。这意味着理念的生命是连续而不连续的。理念的生命部分和片段都是海洋中不相关的水滴，因为理念而相连接。不同维度的理念相互交织，在概率影响下决定对于当前状态下的下一状态。客观来讲，所有状态都是同时存在的，但是在理念的载体的感受角度因为理念的规则存在先后。

因此，存在时空的倒错和以理念为参照的时空不连续、人的时空感受异常现象。比如，大学是在2008年成立的，今年是2021年。但是会存在1805年大学存在的证据。或者突然的存在消失和再现。

外部理念世界就是其中一个很大的理念体。大学是一个小一些的理念体，世界公民是在”“外部理念世界”下的一个理念体。
***** 非日常的日常现象

****** 死亡
死亡是特殊存在。死亡在所有的状态中，只有一个。而无数的规则，从无数的状态中指向死亡。
死亡是意识和存在的消亡，是意识的终结。作为概率平铺下一直存在的死亡。
在规则过于逆反的情况下，突然的「死亡」是世界中一直发生的可能性。从概率的角度来说，死亡的概率是最高的。死亡是一直存在的可能性。
不可言说的非真实状态，突然的死亡，是规则矛盾下的可能结果。
****** 愧疚
****** 缺憾
***** 组成部分的理念与理念的强弱
如果一些组成部分所「相信」的理念相互一致，那么它们所组成的整体会导致环境中规则的扭曲。像万有引力，但是扭曲的是「规则场」。

所以，为了使得大学的物理存在拥有力量和延续存在，大学会将部分处于大学控制范围内的物体（器材，学生，消耗品）逐渐转化为「大学的本身」。包括且不限于器材，建筑，景观，以及空气和空气成分。部分
****** 例子
+ 学校内的食物不能吃。食堂的新鲜菜可以吃。不要在学校存放将要摄入的食物。
+ 多外出进行有氧运动。

***** 董事会的目的
董事会是「世界公民」的集体。为了世界公民理念的存在，合办了「大学」。关于「大学源头」则没有过多的介绍。
放任大学自由生长，只会生长完美的「大学」的存在，但是这和「世界公民」存在不完全符合，所以需要让一些人能够通过大学，成为外界的「世界公民」。为此进行的修改，在大学和师生中都是有的，师生中就是「守则」，大学上则是 =一些机制的修改= 理念体可以直接在思念体内几乎无害地存在。但在无思念体中会无限制地外侵。董事会利用了大学，同时也限制大学的发展。

值得指出的是，无论是「世界公民」理念体还是「大学源头」，都比大学的历史，董事会的历史，民族概念的历史，或者人类存在的历史要长得多了。
***** 来源
一开始位于FB中某个位置的「大学源头」。后来转移到IR楼顶（学校最高的位置）。

*** 关于“世界公民” 在外界的组织
由于 ”“母校情结”，大学被认知为”“和校舍相关的存在”所以无法自如移动位置。在外界的“世界公民”可以行动为大学理念的分散体
**** 反对组织
“世界公民”意识因为其高传染性和潜在危险程度，受到多方组织警惕和调查。自2014年起世界公民在世界各地的数量稳定显著增多（2021年还扩招了）。反对组织对其存在进行调查。
**** 世界公民组织
世界公民理念体的目标有且只有一个：持续自己的存在。世界公民理念体和大学理念体是共生存在。失去一方，另一方会很快死亡。世界公民理念体和大学理念体不是唯一的，但是独特的。每一个理念体都有自己细微的独特处，但是存在相似可容的理念体。相似理念体的携带者聚集并交流的场所，共同理念规则的概率会升高。

** 电子邮件
电子邮件的格式。
幽灵电子邮件

** LMO
LMO是

** 太仓校区
存在或者不存在的太仓校区

** 南/北校区
存在或者不存在的南/北校区

** 学院

*** 环境科学

** 融合式教育
融合式教育可以是谜题的一个核心形式

** 导师体系
每个新生在进校时会被分配一个学友导师。这种关系的建立
有任何xx问题，寻找AA/DA/
+ AA
+ DA
+ 校外导师
+ 学友导师

** 社团结构

*** 艺术协会

*** 探险家协会

*** 学科类社团

*** 伴学社
讲座。

** 课程安排

*** EAP课程
大一一定会有的EAP或二外。
不会有任何形式的三外。
二外包括且只包括日语和西班牙语。法语、德语、盖尔语、拉丁语有相应的选修课。利物浦语就是英语。学校不提供任何形式的利物浦语课程。

*** CCT课程

**** 犀利网

** 宿舍
学校有四个校外宿舍。学校不包括任何校内宿舍。

** 通宵
学校有指定的可通宵场所。不建议在学校通宵。学校对任何在非指定场所通宵期间的发生的突发事故不予评论，不负责任。

** 图书馆

