:PROPERTIES:
:ID:       391C5CF3-2A11-4BC3-ADE3-6F8C6E557B82
:END:
#+title: Neuralscientist
#+HUGO_SECTION:main
I want to be a Neuralscientist, to explore the mechanism of consciousness.
Hope that one day I could figure it out, and make something Really interesting.
* Pathaway
In Order to be a great neuralscientist, I have to get into a major research center of neuralscience.
Therefore, I need academic success.
Hopefully I could go directly for my PhD, but that would require very good grade.
So, I set up the [[id:4972A60D-3727-4422-B73F-BAF3289C1DB8][Academic Machine]].

It definitely need further research, but by now, my plan is
** 1. Very good grade in XJTLU
+ [[id:43B24795-B514-43ED-A8C9-5E03A9652A9A][project: XJTLU]] 
** 2. Very good grade in LU
* Seeking advise
** From youtube video
* How to learn Neuroscience
** Books
+ Roger Carpenter’s ‘Neurophysiology: A Conceptual Approach’.
  + light on details, heavy on concepts
+ Neuroscience by Purves
+ Kandel’s Principle of Neural Sciences
+ (mainly chemistry and biology, with a sprinkle of physics)
+ A Simple Approach to Neuroscience by Abhijeet Statani
** other resources
+ Khan academy, Youtube, and Coursera
+ standford has a behavioral neuroscience course on youtube
+ MIT opencourseware has a lot of math and biology courses that can provide the background knowledge required for most computational neuroscience concepts.
+ https://brainworldmagazine.com/self-studying-neuroscience/
+ youtube video
  + by Indian Institue of Science, Introductory Neuroscience& Neuro instrumentation
    https://www.youtube.com/playlist?list=PLgMDNELGJ1CZ7PWrnrGjz9TrRHJPl2VEy
  + by British Neuroscience Association, Neuroscience Crash Course
    https://www.youtube.com/playlist?list=PLOA0aRJ90NxuIgOC9YGRUT4Y-CsP12bsS
+ Quora
  + https://www.quora.com/What-is-the-best-way-to-start-neuroscience
** Pathaway
*** https://www.quora.com/How-can-I-self-teach-neuroscience?share=1
1. outline the subtopic of focus
2. -> most cited paper under that topic
   1. see what I get & don't get
   2. fullfil the gap
https://www.quora.com/profile/Jean-Luc-105 also interested in CS and Neuro
* Some things to check
** Antonio Damasio
+ Somatic marker hypothesis https://en.wikipedia.org/wiki/Somatic_marker_hypothesis
+ /Self Comes to Mind: Constructing the Conscious Brain/
