:PROPERTIES:
:ID:       BCAC2B73-634A-4A49-8962-40CC2DF03751
:CATEGORY: Athlete
:END:
#+title: Athlete
#+HUGO_SECTION:main
Being a Athlete Means to bear sportsmanship in mind and have willpower

* Background Sound
** Sportsmanship
   It's a attitude to games and sports.
*** Respect
    Respect the sport, the game, and the competitors.
    Knowing that the competitors are just like me, and have put no less effort and willpower into the sport than I do.
    Knowing that the game is as much of a finite game it is, and the game and the sport both converge to the one infinite game.
*** Honest
*** Relationship
    Remember that game along is dead. People/Living play a game, and make it fun. People play the infinite game to make it wider. Without people, no infinite game stand.
** Willpower
   It's the force that make athlete.
*** Control
    Man should be humble, and admit there's no control over everything.
    However, while there's no everlasting life, we still struggle to liveb longer and better.
    While there's no control over everthing nor everytime ==> There in you would always be:
    + Things you can't control
    + Time that your control crash
    Yet we don't give up, and keep pushing and exert that control as clear and focused as we can.
*** Restrain Impulse
    Impulse are bursts of great desire to something. Such great desire would wave people very far.
    By Restraining Impulse, the Captain of the Boat of life ordered the waves and winds, and the Boat would swim well.
**** flaw
     however, this could lead to endless desire.
     Impulse should be the excitement. Diminish the ugly thought with calmness and mindfulness.
* Sports
** Archery
*** ACTIVE Arc-101
    The name's a placeholde, just representing my first Archery Project.
    I tried making it a Ultra project, but I know that currently, it's not my first thing, so maybe someday I'll make a Arc-150-Ultra something.
    In this project, I'll be doing the following things:
    1. Exercise on core strength
    2. Practice and Experiment on Archery
       + Record the Machine
       + keep log
    3. Thinking & Journaling on:
       + What is Archery
       + What Archery is about
       + The underlying principles and spirits/values of Archery
       + How the Backgound Sound apply to Archery in visual and actions
       + How can the model/principles of Archery converge to larger principle/machine that could be apply to other stuffs
       + What's so exciting/fun of Archery that keep me loving it.
    4. Communicating with other people about Archery machine and the thoughts
**** TODO Core Strength
SCHEDULED: <2021-10-13 Wed 08:00 +1d>
:PROPERTIES:
# :STYLE:    habit
:Effort:   40
:LAST_REPEAT: [2022-03-18 Fri 16:46]
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2022-03-18 Fri 16:46]
- State "DONE"       from "TODO"       [2022-03-18 Fri 16:46]
:END:
***** T25 Workout
**** TODO Archery Practice
     SCHEDULED: <2022-03-20 Sun .+2d/4d>
     :PROPERTIES:
     # :STYLE:    habit
     :LAST_REPEAT: [2022-03-18 Fri 16:46]
     :END:
     :LOGBOOK:
     - State "DONE"       from "TODO"       [2022-03-18 Fri 16:46]
     - State "DONE"       from "TODO"       [2022-03-18 Fri 16:46]
     - State "DONE"       from "TODO"       [2021-10-08 Fri 15:52]
     :END:
     Go shooting and practice the ideas every 2 day, no less than every 4 day
     
**** Journaling
     Find in ~Journal.org~, taged ~Archery~
**** Communication Archive
* ACTIVE Work out                                                    :agenda:
** Pull-up
*** Act 3: Folded Knife
[[docview:~/Downloads/学习/书籍资料/生活哲学/运动/体育/囚徒健身（中文完整版）（保罗·威德）.pdf::100][囚徒健身：第三式 折刀引体向上]]
| time             | workout |
| <2021-12-21 Tue> | 1 * 10  |
|                  |         |
**** <2021-12-24 Fri 07:00> Pull-up Practice

**** <2021-12-25 Sat 07:00> Pull-up Practice

**** <2021-12-26 Sun 07:00> Pull-up Practice

**** <2021-12-27 Mon 07:00> Pull-up Practice

**** <2021-12-28 Tue 07:00> Pull-up Practice

**** <2021-12-29 Wed 07:00> Pull-up Practice

**** <2021-12-30 Thu 07:00> Pull-up Practice

**** <2021-12-31 Fri 07:00> Pull-up Practice

**** <2022-01-01 Sat 07:00> Pull-up Practice

**** <2022-01-02 Sun 07:00> Pull-up Practice

**** <2022-01-03 Mon 07:00> Pull-up Practice

*** Act 4 Half Pull up
| time             | workout |
| <2022-01-04 Tue> | 1 * 8   |

** Push-up
*** Act 6: Short length
[[docview:~/Downloads/学习/书籍资料/生活哲学/运动/体育/囚徒健身（中文完整版）（保罗·威德）.pdf::42][囚徒：第六式 窄距俯卧撑]]
| Time             | Workouts |
|------------------+----------|
| [2021-12-21 Tue] | 2 * 10   |
pp
** Running
SCHEDULED: <2022-03-28 Mon +1d>
:PROPERTIES:
:STYLE:    habit
:LAST_REPEAT: [2022-03-28 Mon 14:25]
:END:
:LOGBOOK:
- State "DONE"       from ""           [2022-03-28 Mon 14:25]
- State "DONE"       from              [2022-03-28 Mon 14:25]
:END:
*** habit contract
*** running log
