:PROPERTIES:
:ID:       5E6BD59E-E15A-452B-ABC1-31ABB05BEAE1
:END:
#+title: 2021-12-21
#+HUGO_SECTION:daily
#+filetags: :draft:
#+filetags: :draft:
* Weekly plan
** Overview
*** Declaritive
This week is not going to be trivial. Neither is it going to be all of foreplay and non the small deaths.

I might tend to relate my personal =decitions to the media I encountered=, and that might be bad, but as House's getting things better, maybe that could be a hint for me.

I must feel superial, but not letting it. Being humble and superial could not conflict, as long as I control and aware of them.
*** In Good old schedule
I got:
+ Java coursework to turn in at Thursday
+ Gotta study and finish the CPT107 final sheet
+ Pay attention to further CPT107 assessments
+ Java ethic quiz on lmo
+ Remotely yet important CPT101 Exam
*** In Good new schedule
I got:
+ Neuroscientist
  + on 23, there should be a interesting fest to join
  + All the basics. Inventing them
+ Engineer
  + I'd like to learn the math. Not just learning them, Inventing them
  + Linux...yeah, but later. Javascript and network also. I took steps, notes, and inventional energy
+ Athlete
  + Brand new Archery Practice!!!
  + Brand new Work out Session!!!
    + Arm not strong enough, not endurable enough, therefore:
      + Push-up work out, as in Convict Conditioning
      + Pull-up work out
      + Leg raising work out
+ Artist
  + I should not let jazz limit my style. Though I'm still learning it. I love pop, blues, rock, new age, electronic, and many other things else. Jazz's not superial. I gotta practice and record the Jazz drills, though. The ones, that I like, and find sence in.
*** With myself
+ I don't want to fail other people. That could be my bound to doing things I don't actually want to do. That's not right. I gotta examine on my motives. I gotta take care of myself
+ The Laundrys...Let's do that more often. Plus my desk seems like need a cleaning
+ The great tradition of me treasuring my =energy and conscious= have long been lost, and should be found.
  + Naps
    Can't live with them, can't live without them
  + Meditations
    Horriable not working time while staying conscious. But the days with them is absolutely happier
  + Sleep
    I love the sun, the air, and the mood in the 6 o'clock, and I knew it.
    John have very late schedule, and I have a nice time with him. Other times, nothing could compare with the morning, and they could give me.
  + Food
    I enjoy chinese diet as well as paleo diet. Have myself well fed.
  + Morning page
    Yes, I'm gonna use another non-working time. A LARGE PORTION of it.

