:PROPERTIES:
:ID:       22A8461D-24C0-47E8-BB19-D7976AC59623
:END:
#+title: 2022-03-17
#+HUGO_SECTION:daily
#+filetags: :draft:
#+filetags: :draft:
* Brain dump
:LOGBOOK:
CLOCK: [2022-03-17 Thu 20:55]--[2022-03-17 Thu 21:55] =>  1:00
:END:
What matters?
What am I considering right now?
The Environment, the notes and machines I put just there on my desk, thinking that I could really get a great use of that?

That's Brain dump! That's what I'm constantly thinking about, in the back of my brain. I thought about whether it should be in form a a handwritten literature or being produced using automatic programs, just like org-mode. I personally prefer the muanual approach, maybe because I like writing, and not familiar with the program, but familiar to writing, and the layout of the ideas in my mind, and always forgetting where I put the components of the machine, the program, and how the work. These things, they are not like the prooven fact, but some arbitery ramdom choices. The random choices have their power, they are systematic, and therefore, it's something you could do, without hisitation. It's somewhere to go back to when there's no better ideas. However, they could be not working, as well. Like I have written a "so-called" optimization of a algorithm, but it don't work very well on very much cases, being a proof of =not everything systematic work=

And that's ture, some system could have no sence at all. And that's the dead end, I usually encounter.

What I'm trying to do, is essentially, a expansion of myself. And the expansion, in some ways, is not just wanting to grow in essential strength, like the ability to understand, the ability to memorizem, the ability to connect things, to calculate, to laern, to sing, to kept my hand steady for what ever I want, to control my body and mind, to schedule my thinking and doing, but a expansion of a =desicion system=. I always thought of this systeeem like emacs, but with more autonomouus, that it is a set of working machine, and continue to generate new machines as its expansion, making it grow.

Essentially, all the things I deal with are =decision making=. In terms of business, it's all decision making, but in terms of other fields, like in computer science, it got complicated, involving skills. Now what are skills?
I don't know, to frankly speaking. Skill set? I know the corelating chineses word, and I stopped there for future thinking. It's just like =declare= in clojure, the concept is declare, I heard of it, even familiar with it, but don't know it's meaning, don't know how, in what form it exist. I even don't know if it's a real thing, I just heard of it very often, and I assume it that way. These declared things made up a great part of my life, due to my preference of high-level shi. I feel superior with high level thinking brah brah brah, I like it so much that I don't even care if these theory I am speaking of really exist, really consistent with the reality. I needed the theoroies to prove my class. It's the valarie that drives me to these theories that don't work, that are absolutely trival nonsence, that are not interesting at all. It's this ego that blind my eyes. And it'll carry on this blindness for a very long while, though I could state that I have a much better situation than when I was like 3rd-grade. =Ego= blind me from =Reality=, just like Ray said.

From what I observed, skills are really like machines, which I know is about what. I know that a machine is a set of steps and desicion rules that are engineered to have a result happen. It's a natural science, taking facts as it's material, and use calculation, to have this result, in no time. The time the decision make and action done, the result is definite. Learning a skill set, is like confirm a set of machines. These machines are the steps to do a thing, like =the skill to write essay= correspond to =Essay-writing machine=, and =the skill to play basketball/throw a ball into basket= have the corresponding steps and principles. When talking of =skills=, we are think of ways of doing things, like how to throw a ball, it would involve angle of arm, point of force, and even subtle movement of finger. And when we can naturally do them, as if we are born hard-coded to do so, we say that I have =mastered= the skill. When I can throw a ball from any where into the basket without thinking, I have =mastered= the throwing. And that reveals the 2 seemed contrary description of skill:
+ Systematic
  When talking about a skill, we almost always talk about what to do, and the process is usually fixed, I throw the ball like that in every field. There's principle, like thinking the ball to be pushed against the elbow, followed by theories to support and prove that this process/principle is valid and working, sometimes the best, sometimes efficient. =We could write a book about a skill=. We can say that skills are built from the basic building blocks that we can do withouot thinking. and sometimes, it's categorized against literature/art/phylosophy. Or plain facts, them employing skills to find. them all facts and no what to do about it.
+ Natural
  However, the mastering of a skill is usually judged by how fast people make the decisions of action to take next, and how accurate, even in fields that are not as time-intensive like basketball. It's not a man can do a job with strict reference to a guideline, that he could be considered a skilled worker, but he could do the job, even without thinking about what should be done. The memory, should be so natural, that like they are not arbitery defined human process, which is infinite many, but =plain facts of the world=. Throwing a ball. It's =just easy because that's just how balls should be throwed.= There's only one way that a ball could be throwed, and that's it. or there are just these ways.

  And that's where the =name= became very important. The skills are somehow considered as a sole entity in the world, although there exists very similar processes that could do same things, we needed a fixed impression, to hard-code on our memory, to make it a every instinct.

  高可扩展性和做一件事情并做得很好是两个重要的原则.
